MONKEY_STATE_QUEUED = "QUEUED"
MONKEY_STATE_DISPATCHING = "DISPATCHING"
MONKEY_STATE_DISPATCHING_MACHINE = "DISPATCHING_MACHINE"
MONKEY_STATE_DISPATCHING_INSTALLS = "DISPATCHING_INSTALLS"
MONKEY_STATE_DISPATCHING_SETUP = "DISPATCHING_SETUP"
MONKEY_STATE_RUNNING = "RUNNING"
MONKEY_STATE_CLEANUP = "CLEANING_UP"
MONKEY_STATE_FINISHED = "FINISHED"

MONKEY_TIMEOUT_DISPATCHING_MACHINE = 60 * 4  # 5 min to dispatch machine max
MONKEY_TIMEOUT_DISPATCHING_INSTALLS = 60 * 5  # 5 min to dispatch installs max
MONKEY_TIMEOUT_DISPATCHING_SETUP = 60 * 8  # 8 min to dispatch setup max
MONKEY_TIMEOUT_CLEANUP = 60 * 5  # 5 min to dispatch machine max
